apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: swathipottabathini/react-ts:latest
        ports:
        - containerPort: 3000